/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CotacoesRouteImport } from './routes/cotacoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CotacoesNovaRouteImport } from './routes/cotacoes_.nova'
import { Route as CotacoesIdRouteImport } from './routes/cotacoes_.$id'

const CotacoesRoute = CotacoesRouteImport.update({
  id: '/cotacoes',
  path: '/cotacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CotacoesNovaRoute = CotacoesNovaRouteImport.update({
  id: '/cotacoes_/nova',
  path: '/cotacoes/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const CotacoesIdRoute = CotacoesIdRouteImport.update({
  id: '/cotacoes_/$id',
  path: '/cotacoes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cotacoes': typeof CotacoesRoute
  '/cotacoes/$id': typeof CotacoesIdRoute
  '/cotacoes/nova': typeof CotacoesNovaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cotacoes': typeof CotacoesRoute
  '/cotacoes/$id': typeof CotacoesIdRoute
  '/cotacoes/nova': typeof CotacoesNovaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cotacoes': typeof CotacoesRoute
  '/cotacoes_/$id': typeof CotacoesIdRoute
  '/cotacoes_/nova': typeof CotacoesNovaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cotacoes' | '/cotacoes/$id' | '/cotacoes/nova'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cotacoes' | '/cotacoes/$id' | '/cotacoes/nova'
  id: '__root__' | '/' | '/cotacoes' | '/cotacoes_/$id' | '/cotacoes_/nova'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CotacoesRoute: typeof CotacoesRoute
  CotacoesIdRoute: typeof CotacoesIdRoute
  CotacoesNovaRoute: typeof CotacoesNovaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cotacoes': {
      id: '/cotacoes'
      path: '/cotacoes'
      fullPath: '/cotacoes'
      preLoaderRoute: typeof CotacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotacoes_/nova': {
      id: '/cotacoes_/nova'
      path: '/cotacoes/nova'
      fullPath: '/cotacoes/nova'
      preLoaderRoute: typeof CotacoesNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotacoes_/$id': {
      id: '/cotacoes_/$id'
      path: '/cotacoes/$id'
      fullPath: '/cotacoes/$id'
      preLoaderRoute: typeof CotacoesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CotacoesRoute: CotacoesRoute,
  CotacoesIdRoute: CotacoesIdRoute,
  CotacoesNovaRoute: CotacoesNovaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
