/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CotacoesRouteImport } from './routes/cotacoes'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CotacoesNovaRouteImport } from './routes/cotacoes_.nova'
import { Route as CotacoesIdRouteImport } from './routes/cotacoes_.$id'
import { Route as ClientesNovoRouteImport } from './routes/clientes_.novo'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CotacoesRoute = CotacoesRouteImport.update({
  id: '/cotacoes',
  path: '/cotacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CotacoesNovaRoute = CotacoesNovaRouteImport.update({
  id: '/cotacoes_/nova',
  path: '/cotacoes/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const CotacoesIdRoute = CotacoesIdRouteImport.update({
  id: '/cotacoes_/$id',
  path: '/cotacoes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesNovoRoute = ClientesNovoRouteImport.update({
  id: '/clientes_/novo',
  path: '/clientes/novo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/cotacoes': typeof CotacoesRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/clientes/novo': typeof ClientesNovoRoute
  '/cotacoes/$id': typeof CotacoesIdRoute
  '/cotacoes/nova': typeof CotacoesNovaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/cotacoes': typeof CotacoesRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/clientes/novo': typeof ClientesNovoRoute
  '/cotacoes/$id': typeof CotacoesIdRoute
  '/cotacoes/nova': typeof CotacoesNovaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/cotacoes': typeof CotacoesRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/clientes_/novo': typeof ClientesNovoRoute
  '/cotacoes_/$id': typeof CotacoesIdRoute
  '/cotacoes_/nova': typeof CotacoesNovaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/cotacoes'
    | '/login'
    | '/reset-password'
    | '/clientes/novo'
    | '/cotacoes/$id'
    | '/cotacoes/nova'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/cotacoes'
    | '/login'
    | '/reset-password'
    | '/clientes/novo'
    | '/cotacoes/$id'
    | '/cotacoes/nova'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/cotacoes'
    | '/login'
    | '/reset-password'
    | '/clientes_/novo'
    | '/cotacoes_/$id'
    | '/cotacoes_/nova'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRoute
  CotacoesRoute: typeof CotacoesRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ClientesNovoRoute: typeof ClientesNovoRoute
  CotacoesIdRoute: typeof CotacoesIdRoute
  CotacoesNovaRoute: typeof CotacoesNovaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotacoes': {
      id: '/cotacoes'
      path: '/cotacoes'
      fullPath: '/cotacoes'
      preLoaderRoute: typeof CotacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotacoes_/nova': {
      id: '/cotacoes_/nova'
      path: '/cotacoes/nova'
      fullPath: '/cotacoes/nova'
      preLoaderRoute: typeof CotacoesNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotacoes_/$id': {
      id: '/cotacoes_/$id'
      path: '/cotacoes/$id'
      fullPath: '/cotacoes/$id'
      preLoaderRoute: typeof CotacoesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes_/novo': {
      id: '/clientes_/novo'
      path: '/clientes/novo'
      fullPath: '/clientes/novo'
      preLoaderRoute: typeof ClientesNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRoute,
  CotacoesRoute: CotacoesRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ClientesNovoRoute: ClientesNovoRoute,
  CotacoesIdRoute: CotacoesIdRoute,
  CotacoesNovaRoute: CotacoesNovaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
