/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoosRouteImport } from './routes/voos'
import { Route as TermosCondicoesRouteImport } from './routes/termos-condicoes'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntegracoesRouteImport } from './routes/integracoes'
import { Route as FormasPagamentoRouteImport } from './routes/formas-pagamento'
import { Route as CotacoesRouteImport } from './routes/cotacoes'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReservaIdRouteImport } from './routes/reserva_.$id'
import { Route as ReservaEditarIdRouteImport } from './routes/reserva-editar_.$id'
import { Route as IntegracoesTelegramRouteImport } from './routes/integracoes_.telegram'
import { Route as FinanceiroVendasRouteImport } from './routes/financeiro_.vendas'
import { Route as CotacoesNovaRouteImport } from './routes/cotacoes_.nova'
import { Route as CotacoesIdRouteImport } from './routes/cotacoes_.$id'
import { Route as ClientesNovoRouteImport } from './routes/clientes_.novo'
import { Route as ApiPublicHooksTelegramCheckinRouteImport } from './routes/api/public/hooks/telegram-checkin'

const VoosRoute = VoosRouteImport.update({
  id: '/voos',
  path: '/voos',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosCondicoesRoute = TermosCondicoesRouteImport.update({
  id: '/termos-condicoes',
  path: '/termos-condicoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracoesRoute = IntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const FormasPagamentoRoute = FormasPagamentoRouteImport.update({
  id: '/formas-pagamento',
  path: '/formas-pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const CotacoesRoute = CotacoesRouteImport.update({
  id: '/cotacoes',
  path: '/cotacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservaIdRoute = ReservaIdRouteImport.update({
  id: '/reserva_/$id',
  path: '/reserva/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservaEditarIdRoute = ReservaEditarIdRouteImport.update({
  id: '/reserva-editar_/$id',
  path: '/reserva-editar/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracoesTelegramRoute = IntegracoesTelegramRouteImport.update({
  id: '/integracoes_/telegram',
  path: '/integracoes/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroVendasRoute = FinanceiroVendasRouteImport.update({
  id: '/financeiro_/vendas',
  path: '/financeiro/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const CotacoesNovaRoute = CotacoesNovaRouteImport.update({
  id: '/cotacoes_/nova',
  path: '/cotacoes/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const CotacoesIdRoute = CotacoesIdRouteImport.update({
  id: '/cotacoes_/$id',
  path: '/cotacoes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesNovoRoute = ClientesNovoRouteImport.update({
  id: '/clientes_/novo',
  path: '/clientes/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksTelegramCheckinRoute =
  ApiPublicHooksTelegramCheckinRouteImport.update({
    id: '/api/public/hooks/telegram-checkin',
    path: '/api/public/hooks/telegram-checkin',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/cotacoes': typeof CotacoesRoute
  '/formas-pagamento': typeof FormasPagamentoRoute
  '/integracoes': typeof IntegracoesRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos-condicoes': typeof TermosCondicoesRoute
  '/voos': typeof VoosRoute
  '/clientes/novo': typeof ClientesNovoRoute
  '/cotacoes/$id': typeof CotacoesIdRoute
  '/cotacoes/nova': typeof CotacoesNovaRoute
  '/financeiro/vendas': typeof FinanceiroVendasRoute
  '/integracoes/telegram': typeof IntegracoesTelegramRoute
  '/reserva-editar/$id': typeof ReservaEditarIdRoute
  '/reserva/$id': typeof ReservaIdRoute
  '/api/public/hooks/telegram-checkin': typeof ApiPublicHooksTelegramCheckinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/cotacoes': typeof CotacoesRoute
  '/formas-pagamento': typeof FormasPagamentoRoute
  '/integracoes': typeof IntegracoesRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos-condicoes': typeof TermosCondicoesRoute
  '/voos': typeof VoosRoute
  '/clientes/novo': typeof ClientesNovoRoute
  '/cotacoes/$id': typeof CotacoesIdRoute
  '/cotacoes/nova': typeof CotacoesNovaRoute
  '/financeiro/vendas': typeof FinanceiroVendasRoute
  '/integracoes/telegram': typeof IntegracoesTelegramRoute
  '/reserva-editar/$id': typeof ReservaEditarIdRoute
  '/reserva/$id': typeof ReservaIdRoute
  '/api/public/hooks/telegram-checkin': typeof ApiPublicHooksTelegramCheckinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/cotacoes': typeof CotacoesRoute
  '/formas-pagamento': typeof FormasPagamentoRoute
  '/integracoes': typeof IntegracoesRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos-condicoes': typeof TermosCondicoesRoute
  '/voos': typeof VoosRoute
  '/clientes_/novo': typeof ClientesNovoRoute
  '/cotacoes_/$id': typeof CotacoesIdRoute
  '/cotacoes_/nova': typeof CotacoesNovaRoute
  '/financeiro_/vendas': typeof FinanceiroVendasRoute
  '/integracoes_/telegram': typeof IntegracoesTelegramRoute
  '/reserva-editar_/$id': typeof ReservaEditarIdRoute
  '/reserva_/$id': typeof ReservaIdRoute
  '/api/public/hooks/telegram-checkin': typeof ApiPublicHooksTelegramCheckinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/cotacoes'
    | '/formas-pagamento'
    | '/integracoes'
    | '/login'
    | '/reset-password'
    | '/termos-condicoes'
    | '/voos'
    | '/clientes/novo'
    | '/cotacoes/$id'
    | '/cotacoes/nova'
    | '/financeiro/vendas'
    | '/integracoes/telegram'
    | '/reserva-editar/$id'
    | '/reserva/$id'
    | '/api/public/hooks/telegram-checkin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/cotacoes'
    | '/formas-pagamento'
    | '/integracoes'
    | '/login'
    | '/reset-password'
    | '/termos-condicoes'
    | '/voos'
    | '/clientes/novo'
    | '/cotacoes/$id'
    | '/cotacoes/nova'
    | '/financeiro/vendas'
    | '/integracoes/telegram'
    | '/reserva-editar/$id'
    | '/reserva/$id'
    | '/api/public/hooks/telegram-checkin'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/cotacoes'
    | '/formas-pagamento'
    | '/integracoes'
    | '/login'
    | '/reset-password'
    | '/termos-condicoes'
    | '/voos'
    | '/clientes_/novo'
    | '/cotacoes_/$id'
    | '/cotacoes_/nova'
    | '/financeiro_/vendas'
    | '/integracoes_/telegram'
    | '/reserva-editar_/$id'
    | '/reserva_/$id'
    | '/api/public/hooks/telegram-checkin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRoute
  CotacoesRoute: typeof CotacoesRoute
  FormasPagamentoRoute: typeof FormasPagamentoRoute
  IntegracoesRoute: typeof IntegracoesRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermosCondicoesRoute: typeof TermosCondicoesRoute
  VoosRoute: typeof VoosRoute
  ClientesNovoRoute: typeof ClientesNovoRoute
  CotacoesIdRoute: typeof CotacoesIdRoute
  CotacoesNovaRoute: typeof CotacoesNovaRoute
  FinanceiroVendasRoute: typeof FinanceiroVendasRoute
  IntegracoesTelegramRoute: typeof IntegracoesTelegramRoute
  ReservaEditarIdRoute: typeof ReservaEditarIdRoute
  ReservaIdRoute: typeof ReservaIdRoute
  ApiPublicHooksTelegramCheckinRoute: typeof ApiPublicHooksTelegramCheckinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voos': {
      id: '/voos'
      path: '/voos'
      fullPath: '/voos'
      preLoaderRoute: typeof VoosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-condicoes': {
      id: '/termos-condicoes'
      path: '/termos-condicoes'
      fullPath: '/termos-condicoes'
      preLoaderRoute: typeof TermosCondicoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracoes': {
      id: '/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof IntegracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formas-pagamento': {
      id: '/formas-pagamento'
      path: '/formas-pagamento'
      fullPath: '/formas-pagamento'
      preLoaderRoute: typeof FormasPagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotacoes': {
      id: '/cotacoes'
      path: '/cotacoes'
      fullPath: '/cotacoes'
      preLoaderRoute: typeof CotacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserva_/$id': {
      id: '/reserva_/$id'
      path: '/reserva/$id'
      fullPath: '/reserva/$id'
      preLoaderRoute: typeof ReservaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserva-editar_/$id': {
      id: '/reserva-editar_/$id'
      path: '/reserva-editar/$id'
      fullPath: '/reserva-editar/$id'
      preLoaderRoute: typeof ReservaEditarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracoes_/telegram': {
      id: '/integracoes_/telegram'
      path: '/integracoes/telegram'
      fullPath: '/integracoes/telegram'
      preLoaderRoute: typeof IntegracoesTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro_/vendas': {
      id: '/financeiro_/vendas'
      path: '/financeiro/vendas'
      fullPath: '/financeiro/vendas'
      preLoaderRoute: typeof FinanceiroVendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotacoes_/nova': {
      id: '/cotacoes_/nova'
      path: '/cotacoes/nova'
      fullPath: '/cotacoes/nova'
      preLoaderRoute: typeof CotacoesNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotacoes_/$id': {
      id: '/cotacoes_/$id'
      path: '/cotacoes/$id'
      fullPath: '/cotacoes/$id'
      preLoaderRoute: typeof CotacoesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes_/novo': {
      id: '/clientes_/novo'
      path: '/clientes/novo'
      fullPath: '/clientes/novo'
      preLoaderRoute: typeof ClientesNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/telegram-checkin': {
      id: '/api/public/hooks/telegram-checkin'
      path: '/api/public/hooks/telegram-checkin'
      fullPath: '/api/public/hooks/telegram-checkin'
      preLoaderRoute: typeof ApiPublicHooksTelegramCheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRoute,
  CotacoesRoute: CotacoesRoute,
  FormasPagamentoRoute: FormasPagamentoRoute,
  IntegracoesRoute: IntegracoesRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermosCondicoesRoute: TermosCondicoesRoute,
  VoosRoute: VoosRoute,
  ClientesNovoRoute: ClientesNovoRoute,
  CotacoesIdRoute: CotacoesIdRoute,
  CotacoesNovaRoute: CotacoesNovaRoute,
  FinanceiroVendasRoute: FinanceiroVendasRoute,
  IntegracoesTelegramRoute: IntegracoesTelegramRoute,
  ReservaEditarIdRoute: ReservaEditarIdRoute,
  ReservaIdRoute: ReservaIdRoute,
  ApiPublicHooksTelegramCheckinRoute: ApiPublicHooksTelegramCheckinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
